### ISSUE TITLE
list index out of range on most MP3 files

### ISSUE THREAD

**Issue by tastytea** [AndrewRadev/id3.vim#7]
I'm getting this error on most MP3 files with id3tool 1.2a and neovim 0.8.0:

```
Error detected while processing BufReadCmd Autocommands for "*.mp3"..function id3#ReadMp3[6]..<SNR>101_ReadMp3Id3Tool:
line   17:
E684: list index out of range: 3
E116: Invalid arguments for function append
```

This is one of the files it fails with: [testfile.zip](https://github.com/AndrewRadev/id3.vim/files/10265252/testfile.zip) (it's in the [public domain](https://tomlehrersongs.com/)).

I ran `file` on some files, with this result:

Working:
 - `Audio file with ID3 version 2.4.0, extended header, contains: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, JntStereo`

Not working:
  - `Audio file with ID3 version 2.4.0, unsynchronized frames, contains: MPEG ADTS, layer III, v1, 256 kbps, 44.1 kHz, Stereo`
  - `Audio file with ID3 version 2.4.0, unsynchronized frames, contains: MPEG ADTS, layer III, v1, 256 kbps, 44.1 kHz, Stereo`
  - `Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 192 kbps, 44.1 kHz, Stereo`

**Comment by AndrewRadev** [comment]
Both id3tool and id3v2 have proven to be really fiddly, annoyingly. I might have a solution for id3tool, but I also noticed that id3tool seems to cut off tags above a certain length and I'm really not happy about that :/. The id3v2 tool seems to work better, but on my installation, for a reason I absolutely can't understand, the tool does not have an `-R` tag (see the conversation here: https://github.com/AndrewRadev/id3.vim/pull/5). I'm assuming you might also have the same problem.

I'll work on this problem in the coming weeks.

**Comment by tastytea** [comment]
> but on my installation, for a reason I absolutely can't understand, the tool does not have an `-R` tag (see the conversation here: #5). I'm assuming you might also have the same problem.

Yes, `-R` is in the manpage but the program doesn't recognize it. :woozy_face:

**Comment by AndrewRadev** [comment]
The problem seems to be that, in sourceforge, the 0.1.11 version does have it, while the 0.1.12 version doesn't: https://sourceforge.net/projects/id3v2/files/id3v2/. I feel like maybe on some systems there are people that either patch the support back in, or they ship the 0.1.11 version and call it 0.1.12. I'm not sure at what level this failure is happening is what I'm saying.

I might open an issue to https://archlinux.org/packages/community/x86_64/id3v2/ to discuss at least. Though I'm thinking of doing something more reliable and just writing my own binary, I literally feel like it'll be simpler in the long run.

**Comment by AndrewRadev** [comment]
I have officially decided to just build *another* id3-editing tool, this one with simple json input and output, no need to parse weird regexes: <https://github.com/AndrewRadev/rust-id3-json>.

If you install this tool (you shouldn't need the Rust toolchain, I've added precompiled binaries, but please let me know if they break) and update the Vim plugin, it should work for you. I'll be writing up some documentation soon. I realize it's a layer of inconvenience, but I think in the long run it should be quite reliable.

**Comment by tastytea** [comment]
It works fine with id3-json, thanks!

**Comment by AndrewRadev** [comment]
I also checked `id3tool` with this file, but it only reads id3v1 tags, so there's nothing I can fix with it. And the `id3v2` problem has to do with the missing `-R` flag -- I've tried to implement it without it, but the output is too sloppy.

Because of this, since there's now a working solution, I'll go ahead and close this issue.
